/// @description Insert description here
// You can write your code in this editor
global.currentAnimal = 0;

global.animalsList = ds_list_create();
ds_list_add(global.animalsList, "Alligator")
ds_list_add(global.animalsList, "Bat")
ds_list_add(global.animalsList, "Bear")
ds_list_add(global.animalsList, "Bee")
ds_list_add(global.animalsList, "Canary")
ds_list_add(global.animalsList, "Cat")
ds_list_add(global.animalsList, "Chicken")
ds_list_add(global.animalsList, "Cougar")
ds_list_add(global.animalsList, "Cow")
ds_list_add(global.animalsList, "Coyote")
ds_list_add(global.animalsList, "Dog")
ds_list_add(global.animalsList, "Dolphin")
ds_list_add(global.animalsList, "Donkey")
ds_list_add(global.animalsList, "Dove")
ds_list_add(global.animalsList, "Duck")
ds_list_add(global.animalsList, "Elephant")
ds_list_add(global.animalsList, "Frogmouth")
ds_list_add(global.animalsList, "Goat")
ds_list_add(global.animalsList, "Goose")
ds_list_add(global.animalsList, "Gorilla")
ds_list_add(global.animalsList, "Hawk")
ds_list_add(global.animalsList, "Horse")
ds_list_add(global.animalsList, "Lamb")
ds_list_add(global.animalsList, "Lion")
ds_list_add(global.animalsList, "Macaw")
ds_list_add(global.animalsList, "Monkey")
ds_list_add(global.animalsList, "Mosquito")
ds_list_add(global.animalsList, "Nightingale")
ds_list_add(global.animalsList, "Owl")
ds_list_add(global.animalsList, "Peacock")
ds_list_add(global.animalsList, "Penguin")
ds_list_add(global.animalsList, "Pig")
ds_list_add(global.animalsList, "Pony")
ds_list_add(global.animalsList, "Puma")
ds_list_add(global.animalsList, "Rattlesnake")
ds_list_add(global.animalsList, "Rhinoceros")
ds_list_add(global.animalsList, "Rooster")
ds_list_add(global.animalsList, "Seagull")
ds_list_add(global.animalsList, "Seal")
ds_list_add(global.animalsList, "Sealion")
ds_list_add(global.animalsList, "Sheep")
ds_list_add(global.animalsList, "Tiger")
ds_list_add(global.animalsList, "Vulture")
ds_list_add(global.animalsList, "Whale")